version: "3"

services:
    nginx:
        build:
            context: .docker/nginx
        restart: always
        depends_on:
            - php

    php:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        restart: always
